In [1]:
from main import *
import numpy as np
import sys

import pandas as pd
np.set_printoptions(suppress=True)

In [2]:
def powerset(Sm, Sp):
    PS=[]
    N, M = Sm.shape
    Set = list(range(N))
    for i in range(1 << N):
        ss = [Set[j] for j in range(N) if (i & (1 << j))]
        if len(ss)>=2:
            isA_sp, isA_re = IsAutonomous(Sm, Sp, ss, range(M))
            if isA_sp and isA_re:
                PS.append(ss)

    return PS

In [3]:
n0=20
m0=10
d=5

# 0.3058 	 16.8526 
for rep in [1]:
    print("**** %d ****"%rep)
    input_matrix= np.loadtxt("instances/left_n%dm%dd%d_%d.txt"%(n0,m0,d,rep))
    output_matrix= np.loadtxt("instances/right_n%dm%dd%d_%d.txt"%(n0,m0,d,rep))
    SM=output_matrix-input_matrix
    input_matrix, output_matrix, names_rows, names_cols =CleanData(SM)
    n, m = input_matrix.shape
    SM=output_matrix-input_matrix
    #XX = code.growthRateGraph(output_matrix, input_matrix, 10000)
    XX = code.growthRateGraph(output_matrix, input_matrix, 10000)
    XX_a = code.growthRateGraph_a(output_matrix, input_matrix, 10000, n)
    alpha=XX[1]
    alpha_a=XX_a[1]
    print("alpha=", alpha, "alpha_a= ", alpha_a, XX_a[5])
    S = powerset(input_matrix, output_matrix)   
    print("lenS: ", len(S))
    for s in S:
        if len(s)<=7:
            XX_t=code.growthRateGraph(output_matrix[s,:], input_matrix[s,:], 10000)
            if XX_t[1]>=alpha_a-0.01:
                print("\t ", s, "alpha=", XX_t[1], XX_t[0])

**** 1 ****
Set parameter Username
Academic license - for non-commercial use only - expires 2025-04-19
alpha= 0.7923625595193686 alpha_a=  5.1152373624347485 [ 1  3  4  7  8  9 14 17]


KeyboardInterrupt: 

In [4]:
aa=[0, 2, 7, 8, 9, 13, 17]
xx=[   1. ,         252.18270779,    8.80932362,    6.79363092,    1.,1.,            1.,         1000.,          205.44459869,  558.82319095]

In [4]:
XX_a

(array([  91.67170736,    1.        , 1000.        ,   14.6636836 ,
           1.        ,    1.        ,    1.        ,  185.73682846,
           1.        ,  309.93779153]),
 5.1152373624347485,
 420,
 {0: 0.273950099324798,
  1: 0.3244311840623469,
  2: 0.3707033739515964,
  3: 0.4214608357867446,
  4: 0.5638136429841025,
  5: 0.7061664501814605,
  6: 0.8015943488546309,
  7: 0.9099179095106623,
  8: 1.0522707167080203,
  9: 1.1946235239053784,
  10: 1.262191091472946,
  11: 1.4045438986703038,
  12: 1.5105662050111488,
  13: 1.6123618348808577,
  14: 1.710730047038274,
  15: 1.806280321416142,
  16: 1.8994911616301005,
  17: 1.9907474018986422,
  18: 2.1457817279530493,
  19: 2.2282408024529508,
  20: 2.3100450332466274,
  21: 2.3912835380480972,
  22: 2.4762381814217074,
  23: 2.5606283992708327,
  24: 2.640596651080905,
  25: 2.72029040074836,
  26: 2.799766848386921,
  27: 2.879079074077459,
  28: 2.9582765126466635,
  29: 3.035725653545544,
  30: 3.109396645744729,
  31: 3.1799

In [6]:
input_matrix[aa,:]

array([[ 0.,  0., 87.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 74.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 17.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 55., 74.,  0.,  0.,  0.],
       [35., 51.,  0.,  0.,  0.,  0., 73.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 16.,  0.,  0.],
       [ 0.,  0.,  0., 98.,  5.,  0.,  0.,  0., 83.,  0.]])

In [7]:
output_matrix[aa,:]

array([[13.,  7.,  0.,  0., 38.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 98.,  0.,  0.],
       [ 0., 38., 76., 12., 58., 67., 16.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 45.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 55.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 54., 48.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 42.,  0.,  0.]])

In [8]:
SM_a=output_matrix[aa,:]-input_matrix[aa,:]
SM_a

array([[ 13.,   7., -87.,   0.,  38.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,  98.,   0., -74.],
       [  0.,  38.,  76.,  12.,  58.,  67.,  16.,   0., -17.,   0.],
       [  0.,   0.,   0.,  45.,   0., -55., -74.,   0.,   0.,   0.],
       [-35., -51.,   0.,   0.,   0.,   0., -73.,   0.,   0.,  55.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0., -16.,  54.,  48.],
       [  0.,   0.,   0., -98.,  -5.,   0.,   0.,  42., -83.,   0.]])